name: ubuntu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: cargo build --release --verbose

      - name: Cross-compile Windows
        run: cross build --target x86_64-pc-windows-gnu --release --verbose

      - name: Run tests
        run: cargo test --verbose

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          files: |
            ./target/release/woof-rs
            ./target/x86_64-pc-windows-gnu/release/woof-rs.exe
